name: CI

on:
  push:
    tags: ["*"]
    branches-ignore:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  build-and-run-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: bazel run //:dependency-bazelizer
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
